os:
  - linux
language: python
python:
  - 3.5
  - 3.6
  - 3.7
install:
  - pip install -r requirements.txt
  - pip install coverage
script:
  - coverage run -m unittest tests.pyplant_test
  - coverage run -a -m unittest tests.utils_test
after_success:
  - bash <(curl -s https://codecov.io/bash)